In [17]:
#Exercise 1


#Loads the package Numpy
import numpy as np

# first we simply set up the parameters top match the given criteria in the assignment
beta = 0.9
W = 5
T = 3

# 2. Initialize
#we create a matrix of nan in the shape with 6 rows and 3 columns
Vstar_bi = np.nan+np.zeros([W+1,T])
#another matrix of nans is then created with the same dimension
Cstar_bi = np.nan + np.zeros([W+1,T])
#This line then assigns the last column with an array from 0 to 5(this is 6 lines, which is the same as the w+1)
Cstar_bi[:,T-1] = np.arange(W+1) 
#the next line then creates Vstar, which is the square root of the same matrix
Vstar_bi[:,T-1] = np.sqrt(Cstar_bi[:,T-1])

# 3. solve
# Loop over periods
for t in range(T-2, -1, -1):  #a t variable is then created, which goes from period T-2, until period 0, in steps of minus 1. 
    
    #loop over states
    #creates a variable w, which starts and zero, and stops at w+1(6)
    for w in range(W+1):
        #creates a variable c, which stops at w+1
        c = np.arange(w+1)
        #this is simply a function which gives w-c
        w_c = w - c
        #this creates the vstar_bi matrix from earlier, but with values
        V_next = Vstar_bi[w_c,t+1]
        #this creates a new guess, based on the v_next, beta and the square root of c
        V_guess = np.sqrt(c)+beta*V_next
        #this will return the highest value of the v_guess. it has w rows and t columns
        Vstar_bi[w,t] = np.amax(V_guess)
        #this will return the location of the highest value
        Cstar_bi[w,t] = np.argmax(V_guess)

        
        
print(V_guess)
print(Vstar_bi)
print(Cstar_bi)
#ved ikke helt hvorfor man gør noget af det, men jeg kan nu nogenlunde forstå hvad der bliver gjort

[0]
0
[0 1]
1
[0 1 2]
2
[0 1 2 3]
3
[0 1 2 3 4]
4
[0 1 2 3 4 5]
5
[0]
0
[0 1]
1
[0 1 2]
2
[0 1 2 3]
3
[0 1 2 3 4]
4
[0 1 2 3 4 5]
5
[2.70435871 3.41830519 3.49700577 3.44205081 2.9        2.23606798]
[[0.         0.         0.        ]
 [1.         1.         1.        ]
 [1.9        1.9        1.41421356]
 [2.71       2.31421356 1.73205081]
 [3.12421356 2.68700577 2.        ]
 [3.49700577 3.00484301 2.23606798]]
[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 2.]
 [1. 2. 3.]
 [2. 2. 4.]
 [2. 3. 5.]]


In [21]:
def solve_backwards(beta,W,T):
    # 2. Initialize
    Vstar_bi = np.nan+np.zeros([W+1,T])
    Cstar_bi = np.nan + np.zeros([W+1,T])
    Cstar_bi[:,T-1] = np.arange(W+1) 
    Vstar_bi[:,T-1] = np.sqrt(Cstar_bi[:,T-1])
    # 3. solve
    
    # Loop over periods
    for t in range(T-2, -1, -1):  #from period T-2, until period 0, backwards  
        
        #loop over states
        for w in range(W+1):
            c = np.arange(w+1)
            w_c = w - c
            V_next = Vstar_bi[w_c,t+1]
            V_guess = np.sqrt(c)+beta*V_next
            Vstar_bi[w,t] = np.amax(V_guess)
            Cstar_bi[w,t] = np.argmax(V_guess)

    return Cstar_bi, Vstar_bi

In [23]:
beta = 0.9
W = 5
T = 3
C,V = solve_backwards(beta=beta, W=W, T=T)
print(Cstar_bi)
print(Vstar_bi)


[[0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 2.]
 [1. 2. 3.]
 [2. 2. 4.]
 [2. 3. 5.]]
[[0.         0.         0.        ]
 [1.         1.         1.        ]
 [1.9        1.9        1.41421356]
 [2.71       2.31421356 1.73205081]
 [3.12421356 2.68700577 2.        ]
 [3.49700577 3.00484301 2.23606798]]


In [24]:
# 4. simulate
C_backwards = np.empty(T)
W_now = W

for t in range(T):
    W_now = int(W_now)   # change the type to integegers 0,1,2,3 and so on
    C_backwards[t] = C[W_now,t]  # Use the solution you find above 
    W_now = W_now-C_backwards[t]

print(C_backwards)

[2. 2. 1.]


In [26]:
# 1. Setup 
beta = 0.9
W = 5
T = 10

# 2. - 3. Solve 
C10, V10 = solve_backwards(beta,W,T)  # call function

In [27]:
# define function
def simulate(Cstar,T,W):
    C_backwards = np.empty(T)
    W_now = W
    for t in range(T):
        W_now = int(W_now)   # change the type to integreger 0,1,2,3 and so on
        C_backwards[t] = Cstar[W_now,t]  # I use the solution algorithm 
        W_now = W_now-C_backwards[t]
    return C_backwards

# 4. Simulate
C_sim = simulate(C10,T,W)  # Call function
        
print('Solution for C with T =',T,'and W =', W , ': C =',C_sim)

Solution for C with T = 10 and W = 5 : C = [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
